### ISSUE TITLE
terraform-aviatrix-azure-transit-firenet fails when trying to set a password for firewall instance

### ISSUE THREAD

**Issue by EJtheWise** [terraform-aviatrix-modules/terraform-aviatrix-azure-transit-firenet#3]
When using the module terraform-aviatrix-azure-transit-firenet it fails when trying to set a password for the firewall instance. 

```
Error: failed to create a new firewall instance: Rest API add_firewall_instance Get failed: Failed to launch firewall instance. The Admin Username specified admin is not allowed. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/linux/faq about the username and/or password requirements when creating a VM.

  on .terraform/modules/transit_firenet_1/terraform-aviatrix-azure-transit-firenet-1.0.1/main.tf line 29, in resource "aviatrix_firewall_instance" "firewall_instance_1":
  29: resource "aviatrix_firewall_instance" "firewall_instance_1" {

```

https://github.com/terraform-aviatrix-modules/terraform-aviatrix-azure-transit-firenet/blob/126cfeff97f27132f1752d84ffa4864eae740562/main.tf#L37

Can this be updated to be able to set the username with a variable? Thanks!

**Comment by trvsmtchll** [comment]
Yes we can do that. Glad you found the module and are using it. We had some specific logic in there for checkpoint as you see. Curious which FW image/vendor you're trying to launch.

**Comment by EJtheWise** [comment]
Hey @trvsmtchll thanks for the reply! We are launching a palo alto instance.
